language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.6"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_failure: always
branches:
  except:
    - "/^noci-.*$/"
